name: acceso
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  awesome_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/logo1.png'
  adapative_icon_background: 'assets/icons/logo1.png'

flutter:
  uses-material-design: true
